version: 4.6.0.{build}

cache:
  - C:\Users\appveyor\.ant
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\libewf_64bit
  - C:\libvhdi_64bit
  - C:\libvmdk_64bit
  - C:\zlib
  - C:\sleuthkit
  - '%APPVEYOR_BUILD_FOLDER%\Core\test\qa-functional\data'


image: Visual Studio 2015
platform: x64
environment:
    global:
      TSK_HOME: "C:\\sleuthkit"
      LIBVHDI_HOME: "C:\\libvhdi_64bit"
      LIBVMDK_HOME: "C:\\libvmdk_64bit\\libvmdk"
      LIBEWF_HOME: "C:\\libewf_64bit"
      POSTGRESQL_HOME_64: "C:\\Program Files\\PostgreSQL\\9.5"
      JDK_HOME: C:\Program Files\Java\jdk1.8.0
      PYTHON: "C:\\Python36-x64"

install:
  - ps: choco install ant --ignore-dependencies
  - git clone https://github.com/sleuthkit/sleuthkit
  - ps: $env:Path="C:\Program Files\Java\jdk1.8.0\bin;$($env:Path);C:\ProgramData\chocolatey\lib\ant"
  - set PATH=C:\Python36-x64\';%PATH%
  - ps: >-
      if (!(Test-path -Path $env:TSK_HOME)){
        pushd C:\
        git clone https://github.com/sleuthkit/sleuthkit 2>&1 | %{ "$_" }
        popd
        python setupSleuthkitBranch.py
      } else {
        pushd $env:TSK_HOME
        git reset --hard
        popd
        python setupSleuthkitBranch.py
        pushd $env:TSK_HOME
        git pull 2>&1 | %{ "$_" }
        popd
      }

services:
  - postgresql95

build_script:
  - cd %TSK_HOME%
  - python setupDevRepos.py
  - python win32\updateAndBuildAll.py -m
  - ps: pushd bindings/java
  - ps: ant -version
  - cmd: ant dist-PostgreSQL
  - ps: popd
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: ant -q build
  - cd Core
  - cmd: ant -q test
  - cd ..

test: off
